export enum ActionTypes {
  FETCH_JOKES_START = `FETCH_JOKES_START`,
  FETCH_JOKES_SUCCESS = `FETCH_JOKES_SUCCESS`,
  FETCH_JOKES_FAILURE = `FETCH_JOKES_FAILURE`,
  ADD_JOKE_TO_FAVOURITES = `ADD_JOKE_TO_FAVOURITES`,
  REMOVE_JOKE_FROM_FAVOURITES = `REMOVE_JOKE_FROM_FAVOURITES`,
  ERASE_FAVOURITES = `ERASE_FAVOURITES`,
  CLEAR_ERROR_MESSAGE = `CLEAR_ERROR_MESSAGE`,
}
